name: Build and Test

on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ubuntu
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build . -j8

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build artifacts
          path: build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: Build artifacts

      - name: Run tests
        run: |
          cd build
          ./tester/cardGameTester
