name: Build and Test

on:
  pull_request:
     types:
      - synchronize
jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-image-dev libcunit1-dev
      - name: Ubuntu build
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build . -j8

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build artifacts
          path: build

  macos-build:

    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: BrettDong/setup-sdl2-frameworks@main
        with:
          sdl2: latest
          sdl2-image: latest
      - name: Macosx build
        run: |
          
          mkdir build && cd build
          cmake ..
          cmake --build . -j8

  test:
    needs: linux-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcunit1-dev
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: Build artifacts

      - name: Run tests
        run: |
          cd tester
          chmod a+x cardGameTester
          ./cardGameTester > output.txt
          if grep -q "failures" output.txt; then
            cat output.txt
            exit 1
          fi

